base_url = "https://seg6.space"
title = "seg6"
description = "Personal site and blog of seg6"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false },
]
blog_section_path = "/posts"

back_link_text = "Back"
force_theme = false # false | "light" | "dark"

footer_copyright = ""
footer_credits = false

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false
